#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Get current directory in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables (simple implementation for ES modules)
const loadEnvVars = () => {
    try {
        const envPath = path.join(__dirname, '.env');
        if (fs.existsSync(envPath)) {
            const envFile = fs.readFileSync(envPath, 'utf8');
            envFile.split('\n').forEach(line => {
                const [key, value] = line.split('=');
                if (key && value) {
                    process.env[key.trim()] = value.trim();
                }
            });
        }
    } catch (error) {
        // Silently ignore if .env file doesn't exist
    }
};

loadEnvVars();

// Simple obfuscation function (Base64 encoding with some randomization)
function obfuscate(str) {
    if (!str || str.includes('PLACEHOLDER')) return str;
    
    // Add some randomization and encode
    const randomPrefix = Math.random().toString(36).substring(2, 6);
    const encoded = Buffer.from(str).toString('base64');
    return `${randomPrefix}${encoded}`;
}

// Simple deobfuscation function
function createDeobfuscateFunction() {
    return `
function deobfuscate(str) {
    if (!str || str.includes('PLACEHOLDER')) return str;
    try {
        // Remove the random prefix (first 4 characters) and decode
        const encoded = str.substring(4);
        return atob(encoded);
    } catch (e) {
        return str;
    }
}`;
}

// Firebase configuration with environment variables or placeholder values
const config = {
    apiKey: obfuscate(process.env.FIREBASE_API_KEY || 'PLACEHOLDER_API_KEY'),
    authDomain: obfuscate(process.env.FIREBASE_AUTH_DOMAIN || 'your-project.firebaseapp.com'),
    projectId: obfuscate(process.env.FIREBASE_PROJECT_ID || 'your-project-id'),
    storageBucket: obfuscate(process.env.FIREBASE_STORAGE_BUCKET || 'your-project.firebasestorage.app'),
    messagingSenderId: obfuscate(process.env.FIREBASE_MESSAGING_SENDER_ID || 'PLACEHOLDER_SENDER_ID'),
    appId: obfuscate(process.env.FIREBASE_APP_ID || 'PLACEHOLDER_APP_ID'),
    measurementId: obfuscate(process.env.FIREBASE_MEASUREMENT_ID || 'PLACEHOLDER_MEASUREMENT_ID')
};

// Generate the config file content
const configFileContent = `// Auto-generated Firebase Configuration
// DO NOT EDIT THIS FILE MANUALLY

${createDeobfuscateFunction()}

const firebaseConfigObfuscated = ${JSON.stringify(config, null, 4)};

// Deobfuscate the configuration
const firebaseConfig = {};
for (const [key, value] of Object.entries(firebaseConfigObfuscated)) {
    firebaseConfig[key] = deobfuscate(value);
}

// Export the configuration
export { firebaseConfig };
`;

// Write the config file
fs.writeFileSync(path.join(__dirname, 'js', 'firebase-config.js'), configFileContent);

console.log('✅ Firebase configuration generated successfully!');
console.log('📄 Generated: js/firebase-config.js');
console.log('🌐 Environment:', process.env.NODE_ENV || 'development');
console.log('🔥 Project ID:', process.env.FIREBASE_PROJECT_ID || 'your-project-id');
