name: Report a Bug
description: File a bug or issue related to the mobile app or 3D reconstruction pipeline
title: "[Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve openARMap!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue clearly
      placeholder: e.g. The scan didn't save after pressing Stop
      required: true
