name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: [enhancement]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! We’re building openARMap for public good, and your input helps.

  - type: textarea
    id: what-feature
    attributes:
      label: What's the feature or enhancement?
      description: Be specific. What should it do?
      placeholder: e.g., Add ability to flag low-quality scans in the viewer
      required: true

  - type: textarea
    id: why-needed
    attributes:
      label: Why is it needed?
      description: Explain the problem it solves or value it adds
      placeholder: This helps reduce data noise and improves map quality
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context or inspiration
      description: Link mockups, related issues, or other projects doing something similar
      required: false
