{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-stdlib",
    "version": "1.9.22",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22.jar",
          "url": "kotlin-stdlib-1.9.22.jar",
          "size": 1718956,
          "sha512": "c4ba900639a20a98bc4596c81ac8d70319e5891c28c6cfb2ddcfa841517b32d6e46f7b948fcf04c4270911e0d79888fbff43e9815900b359d286be2ec09e3d3a",
          "sha256": "6abe146c27864138b874ccccfe5f534e3eb923c99a1b7b5d45494ee5694f3e0a",
          "sha1": "d6c44cd08d8f3f9bece8101216dbe6553365c6e3",
          "md5": "c06551ea547417a446386c6ccb198894"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "13.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22.jar",
          "url": "kotlin-stdlib-1.9.22.jar",
          "size": 1718956,
          "sha512": "c4ba900639a20a98bc4596c81ac8d70319e5891c28c6cfb2ddcfa841517b32d6e46f7b948fcf04c4270911e0d79888fbff43e9815900b359d286be2ec09e3d3a",
          "sha256": "6abe146c27864138b874ccccfe5f534e3eb923c99a1b7b5d45494ee5694f3e0a",
          "sha1": "d6c44cd08d8f3f9bece8101216dbe6553365c6e3",
          "md5": "c06551ea547417a446386c6ccb198894"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22-sources.jar",
          "url": "kotlin-stdlib-1.9.22-sources.jar",
          "size": 605561,
          "sha512": "e2e1e583d997f5a79165df67fd26373ab52b1b22cb7ccfcb51269fec1358681c6038a823b3f3733b664ab32866307cf15f499c94262ee3df57b00484f1af7e0a",
          "sha256": "7e1405176c4c7f7b35a9cf446c300eacd0212eaf0006b2142a5f7a99b827ecb0",
          "sha1": "d1b45176c0aeb15a309a4f4a7cd160d4b3c8b733",
          "md5": "cc266a6f65e86c1f7b8ca3c15cb8a2bb"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22-all.jar",
          "url": "kotlin-stdlib-1.9.22-all.jar",
          "size": 139935,
          "sha512": "6add65e67139517764adbee01432d06e79489d166cec3ea3530d62318e1a008cc28de37eb16332d9e15208776a84fba5568e5850c46fd93b19ef8cffc47ae5f6",
          "sha256": "cec38bc3302e72a8aaf9cde436b5a9071ee0331e2ad05e84d8bb897334d7e9d4",
          "sha1": "6c69e7b26179394dafd3c90e630ef763b8c1a267",
          "md5": "4468f2ad5cecac0c0c2639699aafcfc1"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22-common.jar",
          "url": "kotlin-stdlib-1.9.22-common.jar",
          "size": 227385,
          "sha512": "124cc75ebc89fc3a07dc00429ced1fc618896da5f2590bd5a97bd68613359520fc68b9f77dc06a85b4b0e1a2cdeba3b15eb436c0788e2370d40eba96e5c68bff",
          "sha256": "cc1174c1693a242dd6cbc816a527c453e0418494e36c50cdc6578bf40171acdb",
          "sha1": "4c7276a1529397ee6389483a408c57a9c6d4ca7d",
          "md5": "49c4222161afc7b5890e4402978f90ac"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlin-stdlib-1.9.22-common-sources.jar",
          "url": "kotlin-stdlib-1.9.22-common-sources.jar",
          "size": 342180,
          "sha512": "fa638cbc5cfa9290efd0c6630a961fc675c5476324337bedc7a31b2ccd73e7e045ea4b69dbf262d58b852464e80a42ffab45aadf7b8711441f3f156e7a4e075a",
          "sha256": "d63f16fcf070f6fb9ea0d974581193b10e15d51f5bc1d6bcd1587a6ef3426754",
          "sha1": "d446f78926f8a54fda73cc9d424f7f967c4a940d",
          "md5": "726b52bf44382b9b52ab58012f218af3"
        }
      ]
    },
    {
      "name": "nativeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.9.22"
          }
        }
      ]
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.22/kotlin-stdlib-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.22/kotlin-stdlib-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "jsV1ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.22/kotlin-stdlib-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "jsV1RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.22/kotlin-stdlib-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-js/1.9.22/kotlin-stdlib-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.22/kotlin-stdlib-wasm-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.22/kotlin-stdlib-wasm-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-js/1.9.22/kotlin-stdlib-wasm-js-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-js",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.22/kotlin-stdlib-wasm-wasi-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.22/kotlin-stdlib-wasm-wasi-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.22"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlin-stdlib-wasm-wasi/1.9.22/kotlin-stdlib-wasm-wasi-1.9.22.module",
        "group": "org.jetbrains.kotlin",
        "module": "kotlin-stdlib-wasm-wasi",
        "version": "1.9.22"
      }
    }
  ]
}
