blank_issues_enabled: false
contact_links:
  - name: Project Questions & General Discussion
    url: https://github.com/x4dqn/OpenARMap/discussions
    about: For general ideas, design feedback, or discussion, please use the Discussions tab instead of creating an issue.
